### ISSUE TITLE
Bulk density - here we are!

### ISSUE THREAD

**Issue by jmzobitz** [jmzobitz/BES-manuscript#14]
@naupaka 
![image](https://github.com/user-attachments/assets/d6d5d764-2b69-41fa-8bee-9d52df7efaa0)

First pass at this calculation. Red points = NEON measurements at horizon closest to surface.  Boxplot = derived.

By eye, it seems the site-to-site pattern is consistent.

More later.

**Comment by jmzobitz** [comment]
Here is a table of reported bulk density calculations from NEON:

<img width="171" alt="image" src="https://github.com/user-attachments/assets/8a009fd9-06bd-4885-b647-5ff8f20db456">

Notice WREF - does that seem a little low to you?

**Comment by jmzobitz** [comment]
Think I am figuring this out -.

<img width="716" alt="image" src="https://github.com/user-attachments/assets/5accdd62-cc89-4d21-a58a-89c4e193b537">

The bulk density come from different depths from soil cores (I account for this in the neonSoilFlux package).  But when I was writing the code for the previous plots, I was just taking the top bulk density.  I think we need to look at this as a range of values across the entire soil column.  So when we compare the two bulk density calculations, there will end up being two histograms: one derived from the LICOR (as before) and one from NEON.

**Comment by naupaka** [comment]
Maybe visualize via a split violin plot e.g. https://stackoverflow.com/a/73471952 ?

**Comment by jmzobitz** [comment]
Closing this issue, as I think we are going to go in favor of a diffusivity plot.
