### ISSUE TITLE
Year long flux plots

### ISSUE THREAD

**Issue by jmzobitz** [jmzobitz/BES-manuscript#25]
@naupaka 1 of 2 plots I am working on
![flux-results-year](https://github.com/user-attachments/assets/586d0010-eea6-4c28-92ac-434f4ee33ded)

- I average all fluxes to the day (including field data) to avoid over plotting.
- neonSoilFlux results are only at that specific horizontalPosition plot.
- I didn't want to do a calendar year as it didn't make sense for the 2024 field data
- Let me know of any aesthetic changes to make.

Onto the diffusivity boxplots

**Comment by zoey-rw** [comment]
Looking good!! I'd recommend lowering the alpha to increase transparency for the overlapping points (and maybe adding the purple to the color key, or giving a direct annotation e.g. "LICOR calculated")

**Comment by jmzobitz** [comment]
@zoey-rw Can do.

**Comment by naupaka** [comment]
Nice! I think there's also a decision to be made about y axis limits -- I wonder what it looks like with everything on the same y axis limits/scale.

**Comment by naupaka** [comment]
The other thought perhaps related here is the thread we've been discussing about gap-filling. Monthly mean vs weekly mean, for example, and/or some way to show that the data are gap filled for a particular window. Not sure if that goes in this figure or somewhere else.

**Comment by jmzobitz** [comment]
@zoey-rw @naupaka Here is the updated plot with a shared legend (yay!) and uniform axes.
![flux-results-year](https://github.com/user-attachments/assets/673eaf53-9a54-43a6-b363-b2ddeee4d807)

Yes, I agree about the gap-filling of data.  I think if the point it to show the intensive field campaign in an annual context compared to neonSoilFlux, I'd hesitate as that would be a secondary concern.

**Comment by jmzobitz** [comment]
Closing, with updated to push with recent annual and daily flux values.  I am liking this figure!
