### ISSUE TITLE
Diffusivity plots

### ISSUE THREAD

**Issue by jmzobitz** [jmzobitz/BES-manuscript#26]
Related to #25 @naupaka here is the diffusivity plot.

I haven't done the other diffusivity methods yet, but I wonder if this is sufficient enough to convey the point across.
![diffusivity-plot](https://github.com/user-attachments/assets/c3790dce-0c14-45b0-817d-69e5926e37c0)

**Comment by naupaka** [comment]
I think it depends on what the others look like -- are these two the two extremes or are the other methods substantially different?

**Comment by jmzobitz** [comment]
They are the two extremes, and I will make that point in the paper.
