### ISSUE TITLE
x axis limits for flux-results.png could be standardized

### ISSUE THREAD

**Issue by naupaka** [jmzobitz/BES-manuscript#32]
It seems like this could be set to have free_x?

**Comment by jmzobitz** [comment]
I had thought about that - and what was occurring was the grid spacing got wonky (previous drafts of this figure had that problem).  I wanted to showcase some uniformity in the data collection to make ease of comparison when moving across a row.

**Comment by naupaka** [comment]
same as #36

**Comment by naupaka** [comment]
Comment from #36: Flux results - so the plots will be less wide

**Comment by naupaka** [comment]
Addressed in #41
