### ISSUE TITLE
summary plot for water and temperature?

### ISSUE THREAD

**Issue by jmzobitz** [jmzobitz/BES-manuscript#7]
@naupaka: would this type of image be useful for the manuscript?
<img width="396" alt="image" src="https://github.com/user-attachments/assets/09fbf56b-c010-47e8-ade0-2fe8b22c32d7">

This is measured soil temperature and water from the field data you collected. I am thinking of ways to present summary data succinctly. I could also do a bar chart as well (sparklines weren't as effective).

If we decide to move ahead, I think two additional columns including the median and 95% CI of the measurements woul also provide context.  We could also pair this with a traditional table of site information too (which I started in the MS - see lines 31 or search for tbl-neon_sites

**Comment by naupaka** [comment]
I think something like this would be excellent to include -- it shows clearly that SJER and SRER are super dry and hot compared to the others. Are the sparklines/figures like a pdf of the measurements?

**Comment by jmzobitz** [comment]
Yes - it is a pdf of the measurements.  Can do a bar chart, but that might
be too fine grained to distinguish.
LINK <https://gt.albert-rapp.de/fancy_stuff>
LINK
<https://jthomasmock.github.io/gtExtras/articles/plotting-with-gtExtras.html>

I'll forge ahead with it.


***********
John M. Zobitz, PhD
Pronouns: He, him, his

Professor of Mathematics and Data Science
Data Science Program Director
Environmental Studies Program
Augsburg University
2211 Riverside Avenue, CB 93
Minneapolis, MN 55454

Hagfors Center 187
P: (612) 330-1068

**Comment by naupaka** [comment]
I think the pdf probably looks nicer than a histogram, but is there any way to add a quantitative x axis to the plot? Otherwise the qualitative differences are apparent, but hard to place in a broader frame of reference.

**Comment by jmzobitz** [comment]
Yeah, I had thought about that.  Can check up on how to make that work, or
at least having some sort of gridlines with annotation in the caption.
***********
John M. Zobitz, PhD
Pronouns: He, him, his

Professor of Mathematics and Data Science
Data Science Program Director
Environmental Studies Program
Augsburg University
2211 Riverside Avenue, CB 93
Minneapolis, MN 55454

Hagfors Center 187
P: (612) 330-1068

**Comment by jmzobitz** [comment]
Let's close this issue --> I added the mean values of temperature and soil water - it would be cool, but having consistent grid lines would make this a larger table / image than I think we have the space / capacity for.
