### ISSUE TITLE
What is going on with SRER?

### ISSUE THREAD

**Issue by jmzobitz** [jmzobitz/BES-manuscript#9]
@naupaka I used the NEON data viewer to see if I can diagnose what is going on with what we see at SRER:
<img width="566" alt="Screenshot 2024-10-03 at 7 02 22 AM" src="https://github.com/user-attachments/assets/f4be9caf-ef5e-4d3f-97cd-4262c4eebf88">

First thing, here is a handy reference for timestamps at Tucson:
<img width="1046" alt="Screenshot 2024-10-03 at 6 49 46 AM" src="https://github.com/user-attachments/assets/e7651575-4be7-44ec-84b5-4f3fb3bcb9d0">

Some observations:
- Highest values of computed fluxes occur at 19 h local time = 02 h UTC
- Highest values of measured fluxes occur at 13 h local time = 20 h UTC
- Computed fluxes are predicted later.

Soil temperature seems reasonable:
<img width="955" alt="Screenshot 2024-10-03 at 7 01 29 AM" src="https://github.com/user-attachments/assets/04a55104-70c8-4d78-af67-eb11d106407c">

(00:00 UTC = 5:00 PM local time, so that would correspond to the hottest part of the day)

Soil CO2:
<img width="957" alt="Screenshot 2024-10-03 at 7 00 34 AM" src="https://github.com/user-attachments/assets/2961d909-5599-48b2-8c1e-63b868128a23">

Back of the envelope calculation, we would see a higher flux during that time of day because of the gradient (estimated as the difference between heights on the graph)

I am trying to come up with plausible explanations, but scratching my head.

Maybe just as a sanity check, can you plot the raw SRER flux data on your own computer and see how it looks? (Meaning, don't use my processed code).  I am just suspicious I may have a timezone shift somewhere in my code.

Thanks!
John

**Comment by naupaka** [comment]
Do you know if the soil sensors moisture correct their values? I think the LICORs CO2 estimate is concentration for dry air - or which did you use to plot? I wonder if the huge heat swings at SRER have something to do with all this.

**Comment by jmzobitz** [comment]
Closing this issue, as we have sorted out what is going on with this site.
